model_list:
  - model_name: llama3
    litellm_params:
      model: openai/llama3
      api_base: "http://ollama:11434/v1" 
      api_key: sk-1234
  - model_name: llama2  
    litellm_params:
      model: openai/llama2
      api_base: "http://ollama:11434/v1"
      api_key: sk-1234

litellm_settings: 
  drop_params: True
  set_verbose: True

general_settings:
  master_key: sk-1234